language: ruby
env:
  global:
    - DB=mysql
    - TRAVIS=true
  matrix:
    - TASK=spinach
    - TASK=spec
    - TASK=jasmine:ci
before_install:
  - sudo apt-get install libicu-dev -y
  - gem install bundler -v '>= 1.5.1' # Temporary workaround for gem installation error on ruby 2.1.0
branches:
  only:
    - 'master'
rvm:
  - 2.0.0
  - 2.1.0
services:
  - mysql
  - redis-server
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/gitlab.yml.example config/gitlab.yml"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:seed_fu"
script: "bundle exec rake $TASK --trace"
notifications:
  email: false
